spring.application.name=van


#caminho para conectar no banco
# jdbc:h2 indica que h2
# caminho do banco file:./data/bancoJPA
spring.datasource.url=jdbc:h2:file:./data/bdVan

#drive jdbc para conectar no banco h2
spring.datasource.driverClassName=org.h2.Driver

#nome para acessar o banco
spring.datasource.username=sa
#senha do banco(h2 nao tem senha)
spring.datasource.password=


#hablita acessar o banco pelo navegador
spring.h2.console.enabled=true
#caminho para acessar o banco
spring.h2.console.path=/h2-console


#configura o hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#se ouver mudança ele faz um alter table 
spring.jpa.hibernate.ddl-auto=update


#mostra no terminal os comando SQÇ
spring.jpa.show-sql=true